<?php

namespace AppBundle\Repository;

/**
 * GoodsStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsStatRepository extends \Doctrine\ORM\EntityRepository
{
}
