<?php

namespace AppBundle\Repository;

/**
 * GoodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsRepository extends \Doctrine\ORM\EntityRepository
{
}
