<?php

namespace AppBundle\Repository;

/**
 * GoodsParamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsParamRepository extends \Doctrine\ORM\EntityRepository
{
}
