<?php

namespace AppBundle\Repository;

/**
 * GoodsParamValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsParamValueRepository extends \Doctrine\ORM\EntityRepository
{
}
