<?php

namespace AppBundle\Repository;

/**
 * SeoTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeoTextRepository extends \Doctrine\ORM\EntityRepository
{
}
