services:
    app.admin.offer:
        class: AppBundle\Admin\OfferAdmin
        arguments: [~, AppBundle\Entity\Offer, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Офферы }

    app.admin.goods:
        class: AppBundle\Admin\GoodsAdmin
        arguments: [~, AppBundle\Entity\Goods, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Товары }

    app.admin.vendor:
        class: AppBundle\Admin\VendorAdmin
        arguments: [~, AppBundle\Entity\Vendor, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Бренды }
